# Generated by Django 4.0.4 on 2022-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Member1', models.CharField(max_length=200)),
                ('Member2', models.CharField(max_length=200)),
                ('Member3', models.CharField(max_length=200)),
                ('Member4', models.CharField(max_length=200)),
            ],
        ),
    ]
